name: release

on:
  workflow_dispatch:
    inputs:
      prerelease:
        type: boolean

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@1.55.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
    outputs:
      new_tag: ${{ steps.tag.outputs.new_tag }}

  build:
    needs: tag
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["7.0.x"]
        rid:
          [
            "win-x64",
            "linux-x64",
            "linux-arm64",
            "osx-x64",
            "osx-arm64",
          ]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ needs.tag.outputs.new_tag }}

      - name: Setup .NET SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore -r ${{ matrix.rid }}

      - name: Publish
        run: |
          dotnet publish AssetServer.csproj -c Release --no-restore -o ./${{ matrix.rid }} -r ${{ matrix.rid }} --no-self-contained
          zip -r ${{ matrix.rid }}.zip ./${{ matrix.rid }}/*
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.rid }}.zip
          path: ./${{ matrix.rid }}.zip

  make-release:
    needs: 
      - tag
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:    
          ref: ${{ needs.tag.outputs.new_tag }}

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts/
          
      - name: Make release
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: ./artifacts/**/*
          tag_name: ${{ needs.tag.outputs.new_tag }}
